0	!Tether Line control off(0) on(1=Pay In/Out)(2=Tension)(3=Tension+Pay Out)
0       !Parafoil control off(0) on(1)(1=Asymmetric)(2=Symmetric)(3=Everything_On)(4=Incidence)(5=Everything+Incidence)(6=Vertical Angle)(7=LateralOffset)(8=Switching)
1	!Aircraft Control off(0) on(1)
0.2	!KPY - Proportional Gain on Yaw Angle - NOT USED
0.1	!KDY - Derivative Gain on Yaw Angle - NOT USED
0	!KPSI - Not used
1.0	!KPP - Proportional Gain on Roll Angle (8.0)
0.5	!KDP - Derivative Gain on Roll Angle (2.0)
0.0	!KPZ - Proportional Gain on Pitch Angle (4.0)
0.0	!KDZ - Derivative Gain on Pitch Angle (2.0)
0	!KPT - Not used
0.0	!KV - Derivative gain on sideslip (vb) (8.0)
0	!KU
0.2   	!-------
0.1	!---------
2.0	!Kpreel proportional gain on reel controller(2.0)
3.0     !Kdreel derivative gain on reel controller(3.0)
1.0     !Kireel integral gain on reel controller(1.0)
10	!Feedback Update Rate(Hz)
0	!Turn On Sensor Errors
0.1745	!Bias in Bird Roll Angle
0	!Scale Factor in Bird Roll Angle
0.0175	!Standard Deviation of Noise in Bird Roll Angle
0.0017	!Bias in Riser Roll Angle
0	!Scale Factor in Riser Roll Angle
0.00087	!Standard Deviation of Noise in Riser Roll Angle
0.324	!Bias in Tension
0	!Scale Factor in Tension
0.324	!Standard Deviation of Noise in Tension


Scaled Decathalon
-0.02	!Kpy Proportional gain on crossrange (aircraft)
-0.1	!Kdy Derivative gain on crossrange (aircraft)
-0.6	!Kpsi Proportional gain on heading (aircraft)
1.2	!Kpp proportional gain on roll angle (aircraft)
0.1	!Kdp Derivative gain on roll angle (aircraft)
-0.4	!Kpz Proportional gain on altitude (aircraft)
0.15	!Kdz Derivative gain on altitude (aircraft)
-0.3	!Kpt Proportional gain on pitch (aircraft)
-0.15	!Kv proportional gain on sideslip (aircraft)
2.0	!Ku proportional gain on speed (aircraft)    