 type TOWEDSTRUCTURE
  integer :: DYNOFFON = 0                          ! Units: 'nd', Desc: 'Dynamics Flag (0=Off, 1=On)'
  integer :: GRAVOFFON = 0                         ! Units: 'nd', Desc: 'Gravity Flag (0=Off, 1=On)'
  integer :: AEROFLAG = 0                          ! Units: 'nd', Desc: 'Aerodynamics Flag (0=Off, 1=On)'
  integer :: SWEEPOFFON = 0                        ! Units: 'nd', Desc: 'Alpha Sweeps Flag (0=Off, 1=On)'
  integer :: CONTOFFON = 0                         ! Units: 'nd', Desc: 'Contact Flag (0=Off, 1=On)'
  integer :: DQFLAG = 0                            ! Units: 'nd', Desc: 'Data Quality Flag (0=Data Not Loaded Successfully, 1=Data Loaded Successfully)'
  integer :: NLSE = 0                              ! Units: 'nd', Desc: 'Number of Lifting Surface Elements'
  integer :: IP(MAXNLSE) = 1                       ! Units: 'nd', Desc: 'Table Look-up Pointer'
  integer :: TABSIZE(MAXNLSE) = 1                  ! Units: 'nd', Desc: 'Table Size'
  integer :: IPROP(2) = 1                          ! Prop table look up pointer
  integer :: NPROPTAB = 0                          ! Propellor table size
  integer :: THRUSTMOD = 0                         ! 0 = linear , 1 = table look up
  integer :: numNodesNLL = 10                     ! 'nd' Number of Non-linear lifting nodes for us in WingsX
  REAL :: Rde  = 0.                                ! 'nd' Reynolds number in WingsX
  REAL :: CL0  = 0.                                ! 'nd' Zero-AOA lift coefficient WingsX
  REAL :: Sw   = 0.                                ! Reference area (ft^2) - WingsX
  REAL :: bw   = 0.                                ! Reference wingspan (ft) - WingsX
  REAL :: cw   = 0.                                ! Reference chord (ft) - WingsX
  REAL :: Vflt = 0.                                ! Reference Flight speed (ft/s) - WingsX
  REAL :: hx   = 0.                                ! Reference angular momentum (ft) - WingsX
  REAL :: hy   = 0.                                ! Reference angular momentum (ft) - WingsX
  REAL :: hz   = 0.                                ! Reference angular momentum (ft) - WingsX
  real*8 :: C_T_TAB(MAXPROP) = 0                   ! Thrust table
  real*8 :: OMEGA_TAB(MAXPROP) = 0                 ! Rotational speed table
  real*8 :: ADVANCERATIO_TAB(MAXPROP) = 0          ! Advance ratio table
  real*8 :: DELTHRUST_TAB(MAXPROP) = 0             ! control input table
  real*8 :: SAREA = 0                              ! Reference area of aircraft (m^2)
  real*8 :: B = 0                                  ! Wingspan of aircraft(ft)
  real*8 :: C_BAR = 0                              ! Mean chord of aircraft(ft)
  real*8 :: V_T = 0                                ! Trim velocity of aircraft (ft/s)
  real*8 :: PD = 0                                 ! propellor diameter (ft)
  real*8 :: C_L = 0                                ! Lift coefficient (nd)
  real*8 :: C_L_TABLE(SWEEPTABLE) = 0              ! Lift coefficient Table (nd)
  real*8 :: C_D_TABLE(SWEEPTABLE) = 0              ! Drag coefficient Table (nd)
  real*8 :: CXb_TABLE(SWEEPTABLE) = 0              ! Axial Drag coefficient Table (nd)
  real*8 :: CYb_TABLE(SWEEPTABLE) = 0              ! Lateral Drag coefficient Table (nd)
  real*8 :: CZb_TABLE(SWEEPTABLE) = 0              ! Normal Drag coefficient Table (nd)
  real*8 :: Cll_TABLE(SWEEPTABLE) = 0              ! Roll Moment coefficient Table (nd)
  real*8 :: Cm_TABLE(SWEEPTABLE) = 0               ! Pitch moment coefficient Table (nd)
  real*8 :: Cn_TABLE(SWEEPTABLE) = 0               ! Yaw moment coefficient Table (nd)
  real*8 :: AOATABLE(SWEEPTABLE) = 0               ! Angle of attack Table (nd)
  real*8 :: CXb = 0                                ! Axial coefficient (nd)
  real*8 :: CYb = 0                                ! Lateral coefficient (nd)
  real*8 :: CZb = 0                                ! Normal coefficient (nd)
  real*8 :: Cll = 0                                ! Roll moment coefficient (nd)
  real*8 :: Cm = 0                                 ! Pitch moment coefficient (nd)
  real*8 :: Cn = 0                                 ! Yaw moment coefficient (nd)
  real*8 :: C_D = 0                                ! Drag coefficient (nd)
  real*8 :: C_L_0 = 0                              ! zero lift slope
  real*8 :: C_L_ALPHA = 0                          ! lift curve slope
  real*8 :: C_L_ALPHAHAT = 0                       ! dynamic lift curve slope
  real*8 :: C_L_UHAT = 0                           ! increase in lift with speed
  real*8 :: C_L_Q = 0                              ! increase in lift with q
  real*8 :: C_D_Q = 0                              ! increase in drag with q
  real*8 :: C_L_DE = 0                             ! increase in lift with elevator
  real*8 :: C_L_DF = 0                             ! increase in lift with flaps
  real*8 :: C_L_M = 0                              ! lift with mach no.
  real*8 :: C_D_DF = 0                             ! drag with flaps
  real*8 :: C_M_DF = 0                             ! moment with flaps
  real*8 :: C_Y_BETA = 0                           ! side force w.r.t sideslip
  real*8 :: C_Y_P = 0                              ! side force w.r.t roll rate
  real*8 :: C_Y_R = 0                              ! side force w.r.t. yaw rate
  real*8 :: C_Y_DR = 0                             ! side force w.r.t. rudder
  real*8 :: C_Y_DA = 0                             ! side force w.r.t. aileron
  real*8 :: C_D_0 = 0                              ! zero lift drag
  real*8 :: C_D_ALPHA2 = 0                         ! drag polar
  real*8 :: C_D_ALPHAHAT = 0                       ! dynamic drag polar
  real*8 :: C_D_UHAT = 0                           ! increase in drag with speed
  real*8 :: C_D_DE = 0                             ! inrease in drag with elevator
  real*8 :: C_D_M = 0                              ! inrease in drag with mach no.
  real*8 :: C_L_BETA = 0                           ! roll moment w.r.t beta
  real*8 :: C_L_P = 0                              ! roll moment w.r.t roll rate
  real*8 :: C_L_R = 0                              ! roll moment w.r.t. yaw rate
  real*8 :: C_L_DR = 0                             ! roll moment w.r.t. rudder
  real*8 :: C_L_DA = 0                             ! roll moment w.r.t. aileron
  real*8 :: C_roll_ALPHA = 0                       ! roll moment w.r.t. angle of attack
  real*8 :: C_N_ALPHA = 0                          ! yaw moment w.r.t. angle of attack
  real*8 :: C_M_0 = 0                              ! zero lift moment
  real*8 :: C_M_ALPHA = 0                          ! pitch moment curve
  real*8 :: C_M_ALPHAHAT = 0                       ! dynamic moment curve
  real*8 :: C_M_UHAT = 0                           ! increase in pitch moment w.r.t speed
  real*8 :: C_M_Q = 0                              ! pitch moment w.r.t. q
  real*8 :: C_M_DE = 0                             ! pitch moment w.r.t elevator
  real*8 :: C_M_M = 0                              ! pitch moment w.r.t mach no.
  real*8 :: C_M_BETA = 0                           ! pitch moment w.r.t beta
  real*8 :: C_N_BETA = 0                           ! yaw moment w.r.t. beta
  real*8 :: C_N_P = 0                              ! yaw moment w.r.t. roll rate
  real*8 :: C_N_R = 0                              ! yaw moment w.r.t. yaw rate
  real*8 :: C_N_DR = 0                             ! yaw moment w.r.t. rudder
  real*8 :: C_N_DA = 0                             ! yaw moment w.r.t. aileron
  real*8 :: C_X_DT = 0                             ! Thrust w.r.t. delthrust
  real*8 :: C_X_BOX = 0                            ! Box coeff C_X
  real*8 :: C_Y_BOX = 0                            ! Box coeff C_Y
  real*8 :: C_Z_BOX = 0                            ! Box coeff C_Z
  real*8 :: C_L_BOX = 0                            ! Box coeff C_L
  real*8 :: C_M_BOX = 0                            ! Box coeff C_M
  real*8 :: C_N_BOX = 0                            ! Box coeff C_N
  real*8 :: C_L_P_BOX = 0                          ! Box coeff C_L_P
  real*8 :: C_M_Q_BOX = 0                          ! Box coeff C_M_Q
  real*8 :: C_N_R_BOX = 0                          ! Box coeff C_N_R
  real*8 :: AOAREF = 0                             ! Reference Angle of attack
  real*8 :: MASS = 0.0                             ! Units: 'kg', Desc: 'Mass'
  real*8 :: WEIGHT = 0.0                           ! Units: 'lbf', Desc: 'Weight'  
  real*8 :: SLCG = 0.0                             ! Units: 'ft', Desc: 'Stationline of Mass Center'
  real*8 :: BLCG = 0.0                             ! Units: 'ft', Desc: 'Buttline of Mass Center'
  real*8 :: WLCG = 0.0                             ! Units: 'ft', Desc: 'Waterline of Mass Center'
  real*8 :: IXX = 0.0                              ! Units: 'kg m^2', Desc: 'Ixx of Inertia Matrix'
  real*8 :: IYY = 0.0                              ! Units: 'kg m^2', Desc: 'Iyy of Inertia Matrix'
  real*8 :: IZZ = 0.0                              ! Units: 'kg m^2', Desc: 'Izz of Inertia Matrix'
  real*8 :: IXY = 0.0                              ! Units: 'kg m^2', Desc: 'Ixy of Inertia Matrix'
  real*8 :: IXZ = 0.0                              ! Units: 'kg m^2', Desc: 'Ixz of Inertia Matrix'
  real*8 :: IYZ = 0.0                              ! Units: 'kg m^2', Desc: 'Iyz of Inertia Matrix'
  real*8 :: IXXI = 0.0                             ! Units: '1/(kg m^2)', Desc: 'Ixx Inverse of Inertia Matrix'
  real*8 :: IYYI = 0.0                             ! Units: '1/(kg m^2)', Desc: 'Iyy Inverse of Inertia Matrix'
  real*8 :: IZZI = 0.0                             ! Units: '1/(kg m^2)', Desc: 'Izz Inverse of Inertia Matrix'
  real*8 :: IXYI = 0.0                             ! Units: '1/(kg m^2)', Desc: 'Ixy Inverse of Inertia Matrix'
  real*8 :: IXZI = 0.0                             ! Units: '1/(kg m^2)', Desc: 'Ixz Inverse of Inertia Matrix'
  real*8 :: IYZI = 0.0                             ! Units: '1/(kg m^2)', Desc: 'Iyz Inverse of Inertia Matrix'
  real*8 :: TIA(3,3) = 0.0                         ! Units: 'nd', Desc: 'Aircraft to Inertial Frame Transformation Matrix'
  real*8 :: TAI(3,3) = 0.0                         ! Units: 'nd', Desc: 'Inertial to Aircraft Frame Transformation Matrix'
  real*8 :: ELEVATOR = 0                           ! Units: 'rad', Desc: Elevator Command
  real*8 :: RUDDER = 0                             ! Units: 'rad', Desc: RUDDER Command
  real*8 :: AILERON = 0                            ! Units: 'rad', Desc: AILERON Commandn
  real*8 :: FLAPS = 0                              ! Units: 'rad', Desc: FLAP Command
  real*8 :: DELTHRUST = 0                          ! Units: 'rad', Desc: DELTHRUST Command (Total Thrust = Cxdt*DELTHRUST + T0)
  real*8 :: ELEVTRIM  = 0                          ! Units: 'nd', Desc: Stall in airfoil parameters
  real*8 :: CLMAX = 0                              ! Units: 'nd', Desc: Stall in airfoil parameters
  real*8 :: AOAMAX = 0                             ! Units: 'nd', Desc: Stall in airfoil parameters
  real*8 :: AOALINEARMAX = 0                       ! Units: 'nd', Desc: Stall in airfoil parameters
  real*8 :: CLASTALLMAX = 0                        ! Units: 'nd', Desc: Stall in airfoil parameters
  real*8 :: CLMIN = 0                              ! Units: 'nd', Desc: Stall in airfoil parameters
  real*8 :: AOAMIN = 0                             ! Units: 'nd', Desc: Stall in airfoil parameters
  real*8 :: AOALINEARMIN = 0                       ! Units: 'nd', Desc: Stall in airfoil parameters
  real*8 :: CLASTALLMIN = 0                        ! Units: 'nd', Desc: Stall in airfoil parameters
  real*8 :: T0 = 0                                 ! Units: 'nd', Desc: Stall in airfoil parameters
  real*8 :: TPRIME = 0                             ! Units: 'nd', Desc: Stall in airfoil parameters
  real*8 :: TDBLPRIME = 0                          ! Units: 'nd', Desc: Stall in airfoil parameters
  real*8 :: DENEXP = 0                             ! Units: 'nd', Desc: Stall in airfoil parameters ! Throttle = (T0 + TPRIME*V + TDBLPRIME*V^2)*(RHO/RHO_SEA_LEVEL)^DENEXP
  real*8 :: TOFFSET = 0                            ! Units: 'nd', Desc: Stall in airfoil parameters 
  real*8 :: TSLOPE = 0                             ! Units: 'nd', Desc: Stall in airfoil parameters 
  real*8 :: SLLSE(MAXNLSE) = 0.0                   ! Units: 'ft', Desc: 'Stationline of Lifting Surface Element'
  real*8 :: BLLSE(MAXNLSE) = 0.0                   ! Units: 'ft', Desc: 'Waterline of Lifting Surface Element'
  real*8 :: WLLSE(MAXNLSE) = 0.0                   ! Units: 'ft', Desc: 'Buttline of Lifting Surface Element'
  real*8 :: AREALSE(MAXNLSE) = 0.0                 ! Units: 'ft', Desc: 'Lifting Surface Element Reference Area'
  real*8 :: ALPHALSE(MAXNLSE) = 0.0                ! Units: 'rad', Desc: 'Aerodynamic Angle of Attack of Lifting Surface Element'
  real*8 :: PHILSE(MAXNLSE) = 0.0                  ! Units: 'rad', Desc: 'Phi Orientation Angle of Lifting Surface Element'
  real*8 :: GAMLSE(MAXNLSE) = 0.0                  ! Units: 'rad', Desc: 'Gamma Orientation Angle of Lifting Surface Element'
  real*8 :: DELTALSE(MAXNLSE) = 0.0                ! Units: 'rad', Desc: 'Delta Orientation Angle of Lifting Surface Element'
  real*8 :: FXLSE(MAXNLSE) = 0.0                   ! Units: 'nd', Desc: 'Fx Force of Lifting Surface Element in Aircraft Reference Frame'
  real*8 :: FYLSE(MAXNLSE) = 0.0                   ! Units: 'nd', Desc: 'Fy Force of Lifting Surface Element in Aircraft Reference Frame'
  real*8 :: FZLSE(MAXNLSE) = 0.0                   ! Units: 'nd', Desc: 'Fz Force of Lifting Surface Element in Aircraft Reference Frame'
  real*8 :: MXLSE(MAXNLSE) = 0.0                   ! Units: 'nd', Desc: 'Mx Moment of Lifting Surface Element in Aircraft Reference Frame'
  real*8 :: MYLSE(MAXNLSE) = 0.0                   ! Units: 'nd', Desc: 'My Moment of Lifting Surface Element in Aircraft Reference Frame'
  real*8 :: MZLSE(MAXNLSE) = 0.0                   ! Units: 'nd', Desc: 'Mz Moment of Lifting Surface Element in Aircraft Reference Frame'
  real*8 :: ALPHALSETAB(MAXNLSE,MAXNAOA) = 0.0     ! Units: 'rad', Desc: 'Aerodynamic Angle of Attack Table for Lifting Surface Element'
  real*8 :: CLLSETAB(MAXNLSE,MAXNAOA) = 0.0        ! Units: 'rad', Desc: 'Lift Coefficient Table for Lifting Surface Element'
  real*8 :: CDLSETAB(MAXNLSE,MAXNAOA) = 0.0        ! Units: 'rad', Desc: 'Drag Coefficient Table for Lifting Surface Element'
  real*8 :: FXGRAV = 0.0                           ! Units: 'lbf', Desc: 'X Gravity Forces in Body Frame'
  real*8 :: FYGRAV = 0.0                           ! Units: 'lbf', Desc: 'Y Gravity Forces in Body Frame'
  real*8 :: FZGRAV = 0.0                           ! Units: 'lbf', Desc: 'Z Gravity Forces in Body Frame'
  real*8 :: MXGRAV = 0.0                           ! Units: 'N m', Desc: 'X Gravity Moment About CG in Body Frame'
  real*8 :: MYGRAV = 0.0                           ! Units: 'N m', Desc: 'Y Gravity Moment About CG in Body Frame'
  real*8 :: MZGRAV = 0.0                           ! Units: 'N m', Desc: 'Z Gravity Moment About CG in Body Frame'
  real*8 :: FXAERO = 0.0                           ! Units: 'lbf', Desc: 'X Aerodynamic Force in Body Frame'
  real*8 :: FYAERO = 0.0                           ! Units: 'lbf', Desc: 'Y Aerodynamic Force in Body Frame'
  real*8 :: FZAERO = 0.0                           ! Units: 'lbf', Desc: 'Z Aerodynamic Force in Body Frame'
  real*8 :: MXAERO = 0.0                           ! Units: 'N m', Desc: 'X Aerodynamic Moment About CG in Body Frame'
  real*8 :: MYAERO = 0.0                           ! Units: 'N m', Desc: 'Y Aerodynamic Moment About CG in Body Frame'
  real*8 :: MZAERO = 0.0                           ! Units: 'N m', Desc: 'Z Aerodynamic Moment About CG in Body Frame'
  real*8 :: FXCONT = 0.0                           ! Units: 'lbf', Desc: 'X Contact Force in Body Frame'
  real*8 :: FYCONT = 0.0                           ! Units: 'lbf', Desc: 'Y Contact Force in Body Frame'
  real*8 :: FZCONT = 0.0                           ! Units: 'lbf', Desc: 'Z Contact Force in Body Frame'
  real*8 :: MXCONT = 0.0                           ! Units: 'N m', Desc: 'X Contact Moment in Body Frame'
  real*8 :: MYCONT = 0.0                           ! Units: 'N m', Desc: 'Y Contact Moment in Body Frame'
  real*8 :: MZCONT = 0.0                           ! Units: 'N m', Desc: 'Z Contact Moment in Body Frame'
  real*8 :: FXTOTAL = 0.0                          ! Units: 'lbf', Desc: 'X Total Applied Force in Body Frame'
  real*8 :: FYTOTAL = 0.0                          ! Units: 'lbf', Desc: 'Y Total Applied Force in Body Frame'
  real*8 :: FZTOTAL = 0.0                          ! Units: 'lbf', Desc: 'Z Total Applied Force in Body Frame'
  real*8 :: MXTOTAL = 0.0                          ! Units: 'N m', Desc: 'X Total Applied Moment About Mass Center in Body Frame'
  real*8 :: MYTOTAL = 0.0                          ! Units: 'N m', Desc: 'Y Total Applied Moment About Mass Center in Body Frame'
  real*8 :: MZTOTAL = 0.0                          ! Units: 'N m', Desc: 'Z Total Applied Moment About Mass Center in Body Frame'
  real*8 :: INITIALPHI = 0.0                       ! Units: 'rad', Desc: 'Initial Euler Roll Angle of Aircraft'
  real*8 :: INITIALTHETA = 0.0                     ! Units: 'rad', Desc: 'Initial Euler Pitch Angle of Aircraft'
  real*8 :: INITIALPSI = 0.0                       ! Units: 'rad', Desc: 'Initial Euler Yaw Angle of Aircraft'
  real*8 :: INITIALSTATE(13) = 0.0                 ! Units: 'vd', Desc: 'Initial Aircraft State Vector'
  real*8 :: PHI = 0                                ! Units: 'rad', Desc: Aircraft roll angle
  real*8 :: THETA = 0                              ! Units: 'rad', Desc: Aircraft roll angle
  real*8 :: PSI = 0                                ! Units: 'rad', Desc: Aircraft roll angle
  real*8 :: STATE(13) = 0.0                        ! Units: 'vd', Desc: 'Aircraft State Vector'
  real*8 :: STATEPREV(13) = 0.0                    ! Units: 'vd', Desc: 'Aircraft State Vector before camera snapshot'
  real*8 :: STATEDOT(13) = 0.0                     ! Units: 'vd', Desc: 'Aircraft State Vector Derivative'
  real*8 :: VXWIND = 0.0                           ! Units: 'ft/s', Desc: 'Atmospheric Wind Along Inertial I Axis'
  real*8 :: VYWIND = 0.0                           ! Units: 'ft/s', Desc: 'Atmospheric Wind Along Inertial J Axis'
  real*8 :: VZWIND = 0.0                           ! Units: 'ft/s', Desc: 'Atmospheric Wind Along Inertial K Axis'
  
 end type TOWEDSTRUCTURE
